# Site settings
title: Chime Starter
email: norris@codeforamerica.org
description: >
  A starter kit for government sites built with the Chime CMS
baseurl: "" # the subpath of your site, e.g. /blog/
url: "/" # the base hostname & protocol for your site
permalink: /:categories/:title/
city: "Inconsolata"

# Build settings
markdown: kramdown
